import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "SHO Events — Curated Event Agency in Bratislava",
    description:
      "SHO Events crafts atmospheric events end-to-end: dates, brunches, tastings, workshops, corporate and private celebrations in Bratislava.",
  },
  nav: {
    home: "Home",
    about: "About",
    services: "Services",
    formats: "Formats",
    partners: "Partners",
    contacts: "Contacts",
    decor: "Decor Rental",
    portfolio: "Portfolio",
  },
  common: {
    ctaConsult: "Get a Consultation",
    ctaBook: "Submit a Request",
    ctaLearnMore: "Learn More",
    ctaSend: "Send",
    ctaViewAll: "View All",
    ctaWriteUs: "Write to Us",
    formName: "Your name",
    formPhone: "Phone",
    formContact: "Phone or Telegram",
    formEmail: "Email",
    formMessage: "Tell us about your idea",
    formEventType: "Event type",
    formDate: "Preferred date (DD.MM.YYYY)",
    formGuests: "Number of guests",
    formCompany: "Company / brand",
    formPreferredChannels: "Preferred way to reach you",
    formSubmit: "Submit request",
    formSubmitting: "Sending…",
    formSuccessTitle: "Request received",
    formSuccessText:
      "Thank you for reaching out. We'll be in touch within 24 hours to discuss the details.",
    formError: "Something went wrong. Please try again or write to us directly.",
    formRequired: "This field is required",
    menu: "Menu",
    close: "Close",
    rights: "All rights reserved",
    addressLabel: "Bratislava, Slovakia",
    followUs: "Follow us",
    searchPlaceholder: "Search the site",
    searchNoResults: "No results found",
    searchCta: "Open",
    scrollHint: "Scroll",
    since: "since 2021",
  },
  home: {
    heroKicker: "Event Agency · Bratislava",
    heroTitleTop: "We create",
    heroTitleScript: "moments",
    heroTitleBottom: "worth living again",
    heroSubtitle:
      "SHO Events brings people, brands and spaces together — turning ideas into atmospheric events with character.",
    heroCtaPrimary: "Get a Consultation",
    heroCtaSecondary: "Our Services",
    stats: [
      { value: "120+", label: "events curated" },
      { value: "40+", label: "partners & venues" },
      { value: "5", label: "years crafting atmosphere" },
      { value: "98%", label: "guests come back" },
    ],
    introKicker: "Philosophy",
    introTitle: "Not just events — experiences that stay with you",
    introText:
      "We believe every detail matters. From the glass on the table to the light in the room, we shape atmosphere so guests want to linger a little longer in the moment.",
    servicesKicker: "What We Do",
    servicesTitle: "Services for individuals, brands and companies",
    servicesText:
      "From an intimate date for two to a large-scale corporate event — we handle it end-to-end.",
    formatsKicker: "Formats",
    formatsTitle: "Events we love bringing to life",
    processKicker: "How We Work",
    processTitle: "From idea to event",
    processSteps: [
      { number: "01", title: "Discovery", text: "We discuss your idea, goals and the mood you want to set." },
      { number: "02", title: "Concept", text: "We craft the script, visual identity and budget." },
      { number: "03", title: "Preparation", text: "We source the venue, decor, vendors and every detail." },
      { number: "04", title: "The Event", text: "We stay close so you can simply be a guest at your own celebration." },
    ],
    partnersKicker: "For Business",
    partnersTitle: "Restaurants, hotels and brands — let's collaborate",
    partnersText:
      "We help you reach new audiences through joint events, collaborations and atmospheric activations.",
    quote: "Every detail counts. Every moment matters.",
    quoteAuthor: "The SHO Events philosophy",
    ctaTitle: "Ready to create something unforgettable?",
    ctaText: "Tell us about your idea — we'll bring it to life with care for every detail.",
  },
  about: {
    kicker: "About Us",
    title: "We don't just plan events — we create moments",
    lead:
      "SHO Events is a creative agency bringing people, brands and spaces together, turning ideas into events filled with atmosphere, aesthetics and genuine emotion.",
    storyKicker: "Our Story",
    storyTitle: "Where it began",
    storyParagraphs: [
      "SHO Events was born from a simple idea: events should stir feeling, not just fill a calendar. We started with small, intimate gatherings and brunches — and gradually grew into a full-service agency.",
      "Today we organise events of every scale — from dates for two to large corporate celebrations — while holding onto the same principle: attention to detail and honesty in every decision.",
      "We work at the intersection of design, gastronomy and event direction, so every guest feels part of something special.",
    ],
    valuesKicker: "Values",
    valuesTitle: "What every event is built on",
    values: [
      { title: "Aesthetics", text: "We believe in the power of visual language — every detail works toward the overall feeling." },
      { title: "Attention to Detail", text: "From the lighting to the final touch of decor — nothing is too small for us." },
      { title: "Authenticity", text: "We craft atmosphere, not decoration. Genuine emotion can't be faked." },
      { title: "Partnership", text: "We build lasting relationships with brands, venues and guests alike." },
    ],
    approachKicker: "Approach",
    approachTitle: "How we work on every project",
    approachSteps: [
      { title: "Listen", text: "We immerse ourselves in your idea, values and expectations." },
      { title: "Shape a Concept", text: "We design the script, visual style and atmosphere." },
      { title: "Curate the Details", text: "We select decor, vendors, music and table setting." },
      { title: "Stay Close", text: "We're by your side on the day — you can simply enjoy the moment." },
    ],
    quote: "We bring people, brands and spaces together, turning ideas into events.",
    ctaTitle: "Want to get to know us better?",
    ctaText: "Let's talk about your event — over coffee, or in writing.",
  },
  services: {
    kicker: "Our Services",
    title: "Full-cycle event planning",
    lead:
      "We take care of everything — from the first idea to the last detail of decor. Every project is priced individually, tailored to your needs and budget.",
    services: [
      { id: "turnkey", title: "Turnkey Events", description: "Full event organisation, from concept to execution." },
      { id: "brunchMasterclass", title: "Brunches & Workshops", description: "Intimate brunches and creative workshops in a stylish, cosy setting." },
      { id: "corporate", title: "Corporate Events", description: "Team-building, company celebrations and business receptions, end-to-end." },
      { id: "figures3d", title: "Custom 3D Figures & Decor Production", description: "Custom glossy sculptures and decor pieces — a striking accent for any event or brand activation." },
      { id: "dating", title: "Date Planning", description: "Atmospheric, unconventional dates for those who appreciate detail." },
      { id: "rentalDecor", title: "Decor Rental for Styling", description: "A catalogue of tableware, textiles and decor for self-styling across Bratislava." },
    ],
    ctaTitle: "Didn't find what you need?",
    ctaText: "Every project is unique — write to us and we'll shape a solution around your idea.",
  },
  formats: {
    kicker: "Event Formats",
    title: "Events we love shaping atmosphere for",
    lead:
      "Every format has its own rhythm and mood. We adapt our approach to the feeling you want to create.",
    formats: [
      { id: "romantic", title: "Romantic Dates", description: "Intimate evenings for two, with a carefully considered script and decor." },
      { id: "brunch", title: "Brunches & Breakfasts", description: "Daytime gatherings in a warm, light-filled atmosphere." },
      { id: "tasting", title: "Tastings & Chef's Dinners", description: "Gastronomic evenings focused on flavour and presentation." },
      { id: "masterclass", title: "Creative Workshops", description: "From floristry to ceramics — hands-on, memorable events." },
      { id: "private", title: "Birthdays & Anniversaries", description: "Private celebrations with a bespoke concept." },
      { id: "corporate", title: "Corporate Receptions", description: "Business and team events with thoughtful logistics." },
      { id: "brand", title: "Brand Activations", description: "Atmospheric launches and collaboration events." },
      { id: "seasonal", title: "Seasonal & Themed Events", description: "From summer parties to fireside winter receptions." },
    ],
    ctaTitle: "Found your format?",
    ctaText: "Tell us how you picture your event — we'll take care of the rest.",
  },
  partners: {
    kicker: "For Partners",
    title: "Growing audiences together with brands",
    lead:
      "SHO Events helps restaurants, hotels and local brands reach new audiences through atmospheric collaborative events.",
    audiencesKicker: "Who We Work With",
    audiencesTitle: "Our Partners",
    audiences: [
      { title: "Restaurants & Cafés", text: "Themed dinners, tastings and gastronomic evenings." },
      { title: "Hotels", text: "Atmospheric events for guests and the local audience." },
      { title: "Patisseries", text: "Workshops and collaborations built around dessert." },
      { title: "Brands", text: "Activations, product launches and image-building events." },
      { title: "Companies", text: "Corporate events and business receptions." },
    ],
    collabKicker: "Collaboration Formats",
    collabTitle: "How we can work together",
    collabTypes: [
      { title: "Joint Events", text: "We design and run an event under a shared brand." },
      { title: "Venue Placement", text: "We bring guests to your venue through our events." },
      { title: "Styling & Decor", text: "We help shape your space's atmosphere for a specific occasion." },
      { title: "Long-term Partnership", text: "We build a recurring event programme at your venue." },
    ],
    formTitle: "Let's Discuss a Partnership",
    formNote: "Tell us about your brand and we'll propose a collaboration format",
  },
  contacts: {
    kicker: "Contacts",
    title: "Let's Get Acquainted",
    lead: "Reach out however suits you best — we're always happy to discuss a new idea.",
    city: "Bratislava, Slovakia",
    addressNote: "We work across Bratislava and the surrounding area",
    channels: [
      { id: "phone", label: "Phone", value: "+421 918 165 503", href: "tel:+421918165503" },
      { id: "whatsapp", label: "WhatsApp", value: "+421 918 165 503", href: "https://wa.me/421918165503" },
      { id: "instagram", label: "Instagram", value: "@sho.events.sk", href: "https://www.instagram.com/sho.events.sk" },
      { id: "threads", label: "Threads", value: "@sho.events.sk", href: "https://www.threads.com/@sho.events.sk" },
      { id: "email", label: "Email", value: "sho.events.sk@gmail.com", href: "mailto:sho.events.sk@gmail.com" },
    ],
    formTitle: "Write to Us",
    formNote: "We reply within 24 hours",
    eventTypes: [
      "Date",
      "Brunch",
      "Tasting",
      "Workshop",
      "Private event",
      "Corporate event",
      "Other",
    ],
  },
  decor: {
    kicker: "Decor Rental",
    title: "Decor Rental for Styling",
    lead: "A catalogue of tableware, textiles and decor for self-styling — pick up ready sets and build the atmosphere yourself.",
    emptyText: "The catalogue is growing — check back soon.",
    ctaTitle: "Couldn't find the right set?",
    ctaText: "Tell us what mood you're after — we'll put together decor tailored to you.",
  },
  portfolio: {
    kicker: "Portfolio",
    title: "Moments we've created",
    lead: "Real shots from our events — the atmosphere, the details and the emotions that stay with you.",
    emptyText: "The portfolio is still filling up — the first shots will appear here soon.",
    ctaTitle: "Want the same for your event?",
    ctaText: "Tell us about your idea — we'll bring it to life with care for every detail.",
  },
};
