import type { SiteContent } from "./types";

export const sk: SiteContent = {
  meta: {
    title: "SHO Events — agentúra štýlových podujatí v Bratislave",
    description:
      "SHO Events vytvára podujatia na kľúč s atmosférou: rande, brunche, ochutnávky, workshopy, firemné aj súkromné oslavy v Bratislave.",
  },
  nav: {
    home: "Domov",
    about: "O nás",
    services: "Služby",
    formats: "Formáty",
    partners: "Partnerom",
    contacts: "Kontakty",
    decor: "Prenájom dekoru",
    portfolio: "Portfólio",
  },
  common: {
    ctaConsult: "Získať konzultáciu",
    ctaBook: "Odoslať dopyt",
    ctaLearnMore: "Viac informácií",
    ctaSend: "Odoslať",
    ctaViewAll: "Zobraziť všetko",
    ctaWriteUs: "Napíšte nám",
    formName: "Vaše meno",
    formPhone: "Telefón",
    formContact: "Telefón alebo Telegram",
    formEmail: "Email",
    formMessage: "Povedzte nám o svojej predstave",
    formEventType: "Typ podujatia",
    formDate: "Preferovaný dátum (DD.MM.RRRR)",
    formGuests: "Počet hostí",
    formCompany: "Firma / značka",
    formPreferredChannels: "Preferovaný spôsob kontaktu",
    formSubmit: "Odoslať dopyt",
    formSubmitting: "Odosielame…",
    formSuccessTitle: "Dopyt sme prijali",
    formSuccessText:
      "Ďakujeme za dôveru. Ozveme sa vám do 24 hodín a preberieme detaily.",
    formError: "Niečo sa pokazilo. Skúste to znova, alebo nám napíšte priamo.",
    formRequired: "Povinné pole",
    menu: "Menu",
    close: "Zavrieť",
    rights: "Všetky práva vyhradené",
    addressLabel: "Bratislava, Slovensko",
    followUs: "Sledujte nás",
    searchPlaceholder: "Hľadať na stránke",
    searchNoResults: "Nič sa nenašlo",
    searchCta: "Otvoriť",
    scrollHint: "Skrolujte",
    since: "od 2021",
  },
  home: {
    heroKicker: "Event agentúra · Bratislava",
    heroTitleTop: "Vytvárame",
    heroTitleScript: "momenty",
    heroTitleBottom: "ktoré chcete prežiť znova",
    heroSubtitle:
      "SHO Events spája ľudí, značky a priestory — mení nápady na podujatia s atmosférou a charakterom.",
    heroCtaPrimary: "Získať konzultáciu",
    heroCtaSecondary: "Naše služby",
    stats: [
      { value: "120+", label: "zrealizovaných podujatí" },
      { value: "40+", label: "partnerov a lokácií" },
      { value: "5", label: "rokov tvoríme atmosféru" },
      { value: "98%", label: "hostí sa vracia" },
    ],
    introKicker: "Filozofia",
    introTitle: "Nielen podujatia — zážitky, ktoré zostávajú",
    introText:
      "Veríme, že záleží na každom detaile. Od pohára na stole až po svetlo v miestnosti — vytvárame atmosféru tak, aby hostia chceli zostať v momente o čosi dlhšie.",
    servicesKicker: "Čo robíme",
    servicesTitle: "Služby pre jednotlivcov, značky aj firmy",
    servicesText:
      "Od komorného rande pre dvoch až po veľké firemné podujatie — postaráme sa o všetko.",
    formatsKicker: "Formáty",
    formatsTitle: "Podujatia, ktorým radi dávame atmosféru",
    processKicker: "Ako pracujeme",
    processTitle: "Cesta od nápadu k podujatiu",
    processSteps: [
      { number: "01", title: "Zoznámenie", text: "Prebereme váš nápad, ciele a náladu podujatia." },
      { number: "02", title: "Koncept", text: "Vytvoríme scenár, vizuálny štýl a rozpočet." },
      { number: "03", title: "Príprava", text: "Zabezpečíme lokáciu, dekor, dodávateľov a detaily." },
      { number: "04", title: "Podujatie", text: "Sme pri každom momente, aby ste mohli byť hosťom na vlastnej oslave." },
    ],
    partnersKicker: "Pre firmy",
    partnersTitle: "Reštaurácie, hotely a značky — poďme spolupracovať",
    partnersText:
      "Pomáhame osloviť nové publikum prostredníctvom spoločných podujatí, kolaborácií a atmosferických aktivácií.",
    quote: "Na každom detaile záleží. Každý moment je dôležitý.",
    quoteAuthor: "Filozofia SHO Events",
    ctaTitle: "Pripravení vytvoriť niečo nezabudnuteľné?",
    ctaText: "Povedzte nám o svojej predstave — a my ju s citom pre detail privedieme k životu.",
  },
  about: {
    kicker: "O nás",
    title: "Nevytvárame len podujatia — vytvárame momenty",
    lead:
      "SHO Events je kreatívna event agentúra, ktorá spája ľudí, značky a priestory a mení nápady na podujatia plné atmosféry, estetiky a skutočných emócií.",
    storyKicker: "Náš príbeh",
    storyTitle: "Ako to celé začalo",
    storyParagraphs: [
      "SHO Events vzniklo z jednoduchej myšlienky: podujatia majú vyvolávať pocity, nielen zapĺňať kalendár. Začínali sme s komornými stretnutiami a brunchmi — a postupne sme vyrástli na agentúru plného servisu.",
      "Dnes organizujeme podujatia každého rozsahu — od rande pre dvoch až po veľké firemné oslavy — a stále držíme rovnaký princíp: pozornosť k detailu a úprimnosť v každom rozhodnutí.",
      "Pohybujeme sa na priesečníku dizajnu, gastronómie a réžie podujatia, aby sa každý hosť cítil súčasťou niečoho výnimočného.",
    ],
    valuesKicker: "Hodnoty",
    valuesTitle: "Na čom staviame každé podujatie",
    values: [
      { title: "Estetika", text: "Veríme v silu vizuálneho jazyka — každý detail pracuje na celkovom dojme." },
      { title: "Pozornosť k detailu", text: "Od svetla až po posledný dotyk dekoru — pre nás neexistujú maličkosti." },
      { title: "Úprimnosť", text: "Vytvárame atmosféru, nie kulisy. Skutočné emócie sa nedajú predstierať." },
      { title: "Partnerstvo", text: "Budujeme dlhodobé vzťahy so značkami, priestormi aj hosťami." },
    ],
    approachKicker: "Prístup",
    approachTitle: "Ako pracujeme na každom projekte",
    approachSteps: [
      { title: "Počúvame", text: "Ponoríme sa do vášho nápadu, hodnôt a očakávaní." },
      { title: "Tvoríme koncept", text: "Navrhneme scenár, vizuálny štýl a atmosféru." },
      { title: "Kurátorujeme detaily", text: "Vyberáme dekor, dodávateľov, hudbu a prestieranie." },
      { title: "Sme pri vás", text: "V deň podujatia sme nablízku — vy si môžete jednoducho užívať moment." },
    ],
    quote: "Spájame ľudí, značky a priestory a meníme nápady na podujatia.",
    ctaTitle: "Chcete nás spoznať bližšie?",
    ctaText: "Prebereme vaše podujatie osobne — pri káve, alebo v správach.",
  },
  services: {
    kicker: "Naše služby",
    title: "Organizácia podujatí v plnom rozsahu",
    lead:
      "Postaráme sa o všetko — od prvého nápadu až po posledný detail dekoru. Každý projekt oceňujeme individuálne, podľa vašich potrieb a rozpočtu.",
    services: [
      { id: "turnkey", title: "Podujatia na kľúč", description: "Kompletná organizácia podujatia od konceptu po realizáciu." },
      { id: "brunchMasterclass", title: "Brunche a workshopy", description: "Komorné brunche a kreatívne workshopy v štýlovej, útulnej atmosfére." },
      { id: "corporate", title: "Firemné podujatia", description: "Teambuildingy, firemné oslavy a obchodné recepcie na kľúč." },
      { id: "figures3d", title: "Výroba 3D figúr a dekorácií na zákazku", description: "Autorské lesklé sochy a dekorácie na mieru — efektný akcent pre podujatie alebo aktiváciu značky." },
      { id: "dating", title: "Organizácia rande", description: "Atmosferické rande v nezvyčajnom formáte pre milovníkov detailu." },
      { id: "rentalDecor", title: "Prenájom dekoru na prestieranie", description: "Katalóg riadu, textilu a dekoru na samostatné prestieranie po Bratislave." },
    ],
    ctaTitle: "Nenašli ste, čo ste hľadali?",
    ctaText: "Každý projekt je jedinečný — napíšte nám a navrhneme riešenie na mieru.",
  },
  formats: {
    kicker: "Formáty podujatí",
    title: "Podujatia, ktorým radi dávame atmosféru",
    lead:
      "Každý formát má svoj rytmus a náladu. Prístup prispôsobíme pocitu, ktorý chcete odovzdať.",
    formats: [
      { id: "romantic", title: "Romantické rande", description: "Komorné večery pre dvoch s premysleným scenárom a dekorom." },
      { id: "brunch", title: "Brunche a raňajky", description: "Denné podujatia v teplej, vzdušnej atmosfére." },
      { id: "tasting", title: "Ochutnávky a šéfkuchárske večere", description: "Gastronomické večery zamerané na chuť a podanie." },
      { id: "masterclass", title: "Kreatívne workshopy", description: "Od floristiky po keramiku — podujatia so zážitkom." },
      { id: "private", title: "Narodeniny a výročia", description: "Súkromné oslavy s konceptom na mieru." },
      { id: "corporate", title: "Firemné recepcie", description: "Obchodné a tímové podujatia s premyslenou logistikou." },
      { id: "brand", title: "Aktivácie značiek", description: "Atmosferické podujatia pre launch produktu či kolaboráciu." },
      { id: "seasonal", title: "Sezónne a tematické podujatia", description: "Od letných párty po zimné recepcie pri krbe." },
    ],
    ctaTitle: "Našli ste svoj formát?",
    ctaText: "Povedzte nám, aké vidíte svoje podujatie — o zvyšok sa postaráme my.",
  },
  partners: {
    kicker: "Partnerom",
    title: "Rozvíjame publikum spoločne so značkami",
    lead:
      "SHO Events pomáha reštauráciám, hotelom a lokálnym značkám osloviť nové publikum prostredníctvom spoločných podujatí s atmosférou.",
    audiencesKicker: "S kým spolupracujeme",
    audiencesTitle: "Naši partneri",
    audiences: [
      { title: "Reštaurácie a kaviarne", text: "Tematické večere, ochutnávky a gastronomické večery." },
      { title: "Hotely", text: "Atmosferické podujatia pre hostí aj lokálne publikum." },
      { title: "Cukrárne", text: "Workshopy a kolaborácie okolo dezertov." },
      { title: "Značky", text: "Aktivácie, launch produktov a imidžové podujatia." },
      { title: "Firmy", text: "Firemné podujatia a obchodné recepcie." },
    ],
    collabKicker: "Formát spolupráce",
    collabTitle: "Ako môžeme spolupracovať",
    collabTypes: [
      { title: "Spoločné podujatia", text: "Navrhneme a zrealizujeme podujatie pod spoločnou značkou." },
      { title: "Umiestnenie na lokáciu", text: "Prostredníctvom našich podujatí privádzame hostí do vášho priestoru." },
      { title: "Štýling a dekor", text: "Pomôžeme vytvoriť atmosféru vášho priestoru pre konkrétnu príležitosť." },
      { title: "Dlhodobé partnerstvo", text: "Vybudujeme pravidelný program podujatí vo vašom priestore." },
    ],
    formTitle: "Prebereme spoluprácu",
    formNote: "Povedzte nám o svojej značke a navrhneme formát kolaborácie",
  },
  contacts: {
    kicker: "Kontakty",
    title: "Poďme sa spoznať",
    lead: "Napíšte nám spôsobom, ktorý vám vyhovuje — vždy radi preberieme nový nápad.",
    city: "Bratislava, Slovensko",
    addressNote: "Pôsobíme po celej Bratislave a okolí",
    channels: [
      { id: "phone", label: "Telefón", value: "+421 918 165 503", href: "tel:+421918165503" },
      { id: "whatsapp", label: "WhatsApp", value: "+421 918 165 503", href: "https://wa.me/421918165503" },
      { id: "instagram", label: "Instagram", value: "@sho.events.sk", href: "https://www.instagram.com/sho.events.sk" },
      { id: "threads", label: "Threads", value: "@sho.events.sk", href: "https://www.threads.com/@sho.events.sk" },
      { id: "email", label: "Email", value: "sho.events.sk@gmail.com", href: "mailto:sho.events.sk@gmail.com" },
    ],
    formTitle: "Napíšte nám",
    formNote: "Odpovieme do 24 hodín",
    eventTypes: [
      "Rande",
      "Brunch",
      "Ochutnávka",
      "Workshop",
      "Súkromné podujatie",
      "Firemné podujatie",
      "Iné",
    ],
  },
  decor: {
    kicker: "Prenájom dekoru",
    title: "Prenájom dekoru na prestieranie",
    lead: "Katalóg riadu, textilu a dekoru na samostatné prestieranie — vyzdvihnite si hotové sety a vytvorte atmosféru sami.",
    emptyText: "Katalóg sa práve dopĺňa — pozrite sa opäť čoskoro.",
    ctaTitle: "Nenašli ste vhodný set?",
    ctaText: "Povedzte nám, akú atmosféru hľadáte — pripravíme dekor na mieru.",
  },
  portfolio: {
    kicker: "Portfólio",
    title: "Momenty, ktoré sme vytvorili",
    lead: "Skutočné zábery z našich podujatí — atmosféra, detaily a emócie, ktoré zostávajú.",
    emptyText: "Portfólio sa ešte napĺňa — prvé zábery tu čoskoro pribudnú.",
    ctaTitle: "Chcete to isté pre svoje podujatie?",
    ctaText: "Povedzte nám o svojom nápade — s láskou k detailu ho premeníme na realitu.",
  },
};
